<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite hostname="a-0d60a2f203f14" name="Randomly add items to cart" tests="4" failures="3" timestamp="21 Nov 2011 01:16:06 GMT" time="3606.079" errors="0">
  <testcase name="testcaseA" time="1805.688" classname="com.qtpselenium.suite.cart.AddtoCartTest">
    <failure type="com.thoughtworks.selenium.SeleniumException" message="ERROR: Command timed out">
      <![CDATA[com.thoughtworks.selenium.SeleniumException: ERROR: Command timed out
	at com.thoughtworks.selenium.HttpCommandProcessor.throwAssertionFailureExceptionOrError(HttpCommandProcessor.java:97)
	at com.thoughtworks.selenium.HttpCommandProcessor.doCommand(HttpCommandProcessor.java:91)
	at com.thoughtworks.selenium.DefaultSelenium.open(DefaultSelenium.java:335)
	at com.qtpselenium.suite.cart.AddtoCartTest.selectRandomItem(AddtoCartTest.java:95)
	at com.qtpselenium.suite.cart.AddtoCartTest.testcaseA(AddtoCartTest.java:46)
... Removed 25 stack frames]]>
    </failure>
  </testcase>
  <testcase name="testcaseA" time="0.0" classname="com.qtpselenium.suite.cart.AddtoCartTest">
    <skipped/>
  </testcase>
  <testcase name="testcaseA" time="1800.047" classname="com.qtpselenium.suite.cart.AddtoCartTest">
    <failure type="com.thoughtworks.selenium.SeleniumException" message="ERROR: Command timed out">
      <![CDATA[com.thoughtworks.selenium.SeleniumException: ERROR: Command timed out
	at com.thoughtworks.selenium.HttpCommandProcessor.throwAssertionFailureExceptionOrError(HttpCommandProcessor.java:97)
	at com.thoughtworks.selenium.HttpCommandProcessor.doCommand(HttpCommandProcessor.java:91)
	at com.thoughtworks.selenium.DefaultSelenium.open(DefaultSelenium.java:335)
	at com.qtpselenium.suite.cart.AddtoCartTest.selectRandomItem(AddtoCartTest.java:95)
	at com.qtpselenium.suite.cart.AddtoCartTest.testcaseA(AddtoCartTest.java:46)
... Removed 25 stack frames]]>
    </failure>
  </testcase>
  <testcase name="testcaseA" time="0.0" classname="com.qtpselenium.suite.cart.AddtoCartTest">
    <failure type="com.thoughtworks.selenium.SeleniumException" message="ERROR Server Exception: unexpected command json={command:&amp;quot;open&amp;quot;,target:&amp;quot;/&amp;quot;,value:&amp;quot;&amp;quot;} in place before new command open could be added">
      <![CDATA[com.thoughtworks.selenium.SeleniumException: ERROR Server Exception: unexpected command json={command:"open",target:"/",value:""} in place before new command open could be added
	at com.thoughtworks.selenium.HttpCommandProcessor.throwAssertionFailureExceptionOrError(HttpCommandProcessor.java:97)
	at com.thoughtworks.selenium.HttpCommandProcessor.doCommand(HttpCommandProcessor.java:91)
	at com.thoughtworks.selenium.DefaultSelenium.open(DefaultSelenium.java:335)
	at com.qtpselenium.suite.cart.AddtoCartTest.selectRandomItem(AddtoCartTest.java:95)
	at com.qtpselenium.suite.cart.AddtoCartTest.testcaseA(AddtoCartTest.java:46)
... Removed 25 stack frames]]>
    </failure>
  </testcase>
</testsuite>
