<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitReportReporter -->
<testsuite hostname="ashish-PC" name="com.qtpselenium.framework.suiteA.PortFolioTest" tests="6" failures="4" timestamp="13 Mar 2015 03:19:24 GMT" time="0.690" errors="0">
  <testcase name="deletePortFolioTest" time="0.080" classname="com.qtpselenium.framework.suiteA.PortFolioTest">
    <failure type="org.testng.SkipException" message="Skipping the test deletePortFolioTest as runmode of test was NO">
      <![CDATA[org.testng.SkipException: Skipping the test deletePortFolioTest as runmode of test was NO
	at com.qtpselenium.framework.util.Utility.validateTestExecution(Utility.java:110)
	at com.qtpselenium.framework.suiteA.PortFolioTest.deletePortFolioTest(PortFolioTest.java:56)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:84)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:714)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:901)
	at org.testng.internal.TestMethodWithDataProviderMethodWorker.call(TestMethodWithDataProviderMethodWorker.java:73)
	at org.testng.internal.TestMethodWithDataProviderMethodWorker.call(TestMethodWithDataProviderMethodWorker.java:14)
	at java.util.concurrent.FutureTask.run(Unknown Source)
	at java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source)
	at java.util.concurrent.FutureTask.run(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at java.lang.Thread.run(Unknown Source)
]]>
    </failure>
  </testcase> <!-- deletePortFolioTest -->
  <testcase name="deletePortFolioTest" time="0.080" classname="com.qtpselenium.framework.suiteA.PortFolioTest">
    <failure type="org.testng.SkipException" message="Skipping the test deletePortFolioTest as runmode of test was NO">
      <![CDATA[org.testng.SkipException: Skipping the test deletePortFolioTest as runmode of test was NO
	at com.qtpselenium.framework.util.Utility.validateTestExecution(Utility.java:110)
	at com.qtpselenium.framework.suiteA.PortFolioTest.deletePortFolioTest(PortFolioTest.java:56)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:84)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:714)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:901)
	at org.testng.internal.TestMethodWithDataProviderMethodWorker.call(TestMethodWithDataProviderMethodWorker.java:73)
	at org.testng.internal.TestMethodWithDataProviderMethodWorker.call(TestMethodWithDataProviderMethodWorker.java:14)
	at java.util.concurrent.FutureTask.run(Unknown Source)
	at java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source)
	at java.util.concurrent.FutureTask.run(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at java.lang.Thread.run(Unknown Source)
]]>
    </failure>
  </testcase> <!-- deletePortFolioTest -->
  <testcase name="renamePortFolioTest" time="0.073" classname="com.qtpselenium.framework.suiteA.PortFolioTest">
    <failure type="org.testng.SkipException" message="Skipping the test renamePortFolioTest as runmode of test was NO">
      <![CDATA[org.testng.SkipException: Skipping the test renamePortFolioTest as runmode of test was NO
	at com.qtpselenium.framework.util.Utility.validateTestExecution(Utility.java:110)
	at com.qtpselenium.framework.suiteA.PortFolioTest.renamePortFolioTest(PortFolioTest.java:39)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:84)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:714)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:901)
	at org.testng.internal.TestMethodWithDataProviderMethodWorker.call(TestMethodWithDataProviderMethodWorker.java:73)
	at org.testng.internal.TestMethodWithDataProviderMethodWorker.call(TestMethodWithDataProviderMethodWorker.java:14)
	at java.util.concurrent.FutureTask.run(Unknown Source)
	at java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source)
	at java.util.concurrent.FutureTask.run(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at java.lang.Thread.run(Unknown Source)
]]>
    </failure>
  </testcase> <!-- renamePortFolioTest -->
  <testcase name="renamePortFolioTest" time="0.123" classname="com.qtpselenium.framework.suiteA.PortFolioTest">
    <failure type="org.testng.SkipException" message="Skipping the test renamePortFolioTest as runmode of test was NO">
      <![CDATA[org.testng.SkipException: Skipping the test renamePortFolioTest as runmode of test was NO
	at com.qtpselenium.framework.util.Utility.validateTestExecution(Utility.java:110)
	at com.qtpselenium.framework.suiteA.PortFolioTest.renamePortFolioTest(PortFolioTest.java:39)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:84)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:714)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:901)
	at org.testng.internal.TestMethodWithDataProviderMethodWorker.call(TestMethodWithDataProviderMethodWorker.java:73)
	at org.testng.internal.TestMethodWithDataProviderMethodWorker.call(TestMethodWithDataProviderMethodWorker.java:14)
	at java.util.concurrent.FutureTask.run(Unknown Source)
	at java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source)
	at java.util.concurrent.FutureTask.run(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at java.lang.Thread.run(Unknown Source)
]]>
    </failure>
  </testcase> <!-- renamePortFolioTest -->
  <testcase name="createPortFolioTest" time="0.172" classname="com.qtpselenium.framework.suiteA.PortFolioTest"/>
  <testcase name="createPortFolioTest" time="0.162" classname="com.qtpselenium.framework.suiteA.PortFolioTest"/>
</testsuite> <!-- com.qtpselenium.framework.suiteA.PortFolioTest -->
